# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb89dcd277b19fec9583b7728befd3b6b2e4df1d5fbce687b4a793575d1fa8fa1293aa60da1b1baba60fed0fb2871031debf2c570b435272db6e6e2b7928c81f

test:
  secret_key_base: b1852019616e864a6d56a6c06e9e9ee47d9c08493053121f915105b58353a25637638518e5e47d1c92c164141835fd01cd591b32744535317238dab950024bda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
